version: '3.8'

volumes:
    bookstack-mysql-data:
        driver: local

services:
    mysql:
        image: mysql:latest
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: bookstacksql
        environment:
            - MYSQL_DATABASE=bookstack
            - MYSQL_USER=daniel
            - MYSQL_PASSWORD=daniel
            - MYSQL_ROOT_PASSWORD=root
            - TZ=America/Sao_Paulo
        volumes:
            - bookstack-mysql-data:/var/lib/mysql
        working_dir: /srv/vhosts/phpApp
        ports:
            - 13307:3306

    myapp:
        build: .
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        container_name: bookstackphp
        environment:
            - DOCKER=1
            - DEV_MODE=1
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=bookstack
            - DB_NAME_LOG=bookstack
            - DB_USER=bookstack
            - DB_PASS=bookstack
            - DB_DATABASE=bookstack
            - DB_USERNAME=daniel
            - DB_PASSWORD=daniel
            - BK_SYNC=1
            - XDEBUG_ENABLED=true
            - NODE_OPTIONS=--openssl-legacy-provider
        ports:
            - 9876:80
        depends_on:
            - mysql
